name: Run Pytest

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Cambia según la versión que uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations (opcional, si las necesitas)
        run: |
          python manage.py makemigrations
          python manage.py migrate
          python manage.py loaddata ./Tienda/fixtures/datos_prueba.json

      - name: Run pytest
        run: pytest Tienda/pytest
