# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPagarcontrareembolso():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pagarcontrareembolso(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 696)
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(2) .add-to-cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(3) .add-to-cart-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-shopping-cart").click()
    self.driver.find_element(By.ID, "confirmar").click()
    self.driver.find_element(By.ID, "id_nombre").click()
    self.driver.find_element(By.ID, "id_nombre").send_keys("Isaac")
    self.driver.find_element(By.ID, "id_apellidos").send_keys("Solis")
    self.driver.find_element(By.ID, "id_direccion").send_keys("Calle Tarfia")
    self.driver.find_element(By.ID, "id_email").send_keys("isaacsolis@gmail.com")
    self.driver.find_element(By.ID, "id_metodo_de_pago").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_metodo_de_pago > option:nth-child(1)").click()
    self.driver.find_element(By.ID, "id_forma_entrega").click()
    self.driver.find_element(By.CSS_SELECTOR, "#id_forma_entrega > option:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div > button:nth-child(1)").click()
  
