# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditarCategoria():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editarCategoria(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 695)
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(4) > span").click()
    self.driver.find_element(By.NAME, "email").send_keys("grupo17@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-item:nth-child(2) .edit-button").click()
    self.driver.find_element(By.ID, "descripcion").click()
    self.driver.find_element(By.ID, "descripcion").click()
    element = self.driver.find_element(By.ID, "descripcion")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "descripcion").click()
    self.driver.find_element(By.ID, "descripcion").send_keys("Esto es una prueba de edicion de categoria")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".category-item:nth-child(2) .edit-button").click()
    self.driver.find_element(By.LINK_TEXT, "Cancelar").click()
  
