# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistro():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registro(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 695)
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
    self.driver.find_element(By.NAME, "first_name").click()
    self.driver.find_element(By.NAME, "first_name").send_keys("Isaac")
    self.driver.find_element(By.NAME, "last_name").send_keys("Solis")
    self.driver.find_element(By.NAME, "email").send_keys("isaacsolis@gmail.com")
    self.driver.find_element(By.NAME, "username").send_keys("Isaac")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.NAME, "confirm_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
  
