# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuscarPorNombre():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buscarPorNombre(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 697)
    self.driver.find_element(By.ID, "filter-name").click()
    self.driver.find_element(By.ID, "filter-name").send_keys("Lavanda")
    self.driver.find_element(By.ID, "filter-name").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(1) h3").click()
    self.driver.find_element(By.CSS_SELECTOR, "a > .navbar-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(9) h3").click()
    self.driver.find_element(By.CSS_SELECTOR, "a > .navbar-link").click()
  
