# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCrearCategoria():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crearCategoria(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 695)
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(4) > span").click()
    self.driver.find_element(By.NAME, "email").send_keys("grupo17@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.LINK_TEXT, "Crear nueva categoría").click()
    self.driver.find_element(By.NAME, "nombre").click()
    self.driver.find_element(By.NAME, "nombre").send_keys("Prueba")
    self.driver.find_element(By.NAME, "descripcion").click()
    self.driver.find_element(By.NAME, "descripcion").send_keys("Esto es una descipcion de prueba")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.LINK_TEXT, "Crear nueva categoría").click()
    self.driver.find_element(By.NAME, "nombre").click()
    self.driver.find_element(By.NAME, "nombre").send_keys("Prueba2")
    self.driver.find_element(By.NAME, "descripcion").click()
    self.driver.find_element(By.NAME, "descripcion").send_keys("Esto es una segunda prueba pero de cancelacion")
    self.driver.find_element(By.LINK_TEXT, "Cancelar").click()
  
