# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCRUDProductos():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cRUDProductos(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.CSS_SELECTOR, ".cta > span").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("grupo17@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # Espera y maneja el pop-up (alerta) que aparece después de iniciar sesión
    WebDriverWait(self.driver, 10).until(
          expected_conditions.alert_is_present()
        )
    alert = self.driver.switch_to.alert
    alert.accept()  # Hace clic en "OK" en el pop-up
    self.driver.find_element(By.CSS_SELECTOR, "#productos > .create-button").click()
    self.driver.find_element(By.NAME, "nombre").click()
    self.driver.find_element(By.NAME, "nombre").send_keys("Prueba")
    self.driver.find_element(By.NAME, "precio").send_keys("50")
    self.driver.find_element(By.NAME, "stock").send_keys("520")
    self.driver.find_element(By.NAME, "descripcion").send_keys("Esto es una descipcion de prueba de creacion")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(13) .update-button").click()
    self.driver.find_element(By.ID, "nombre").click()
    self.driver.find_element(By.ID, "nombre").send_keys("Prueba edicion")
    self.driver.find_element(By.ID, "descripcion").click()
    self.driver.find_element(By.ID, "descripcion").send_keys("Esto es una descipcion de prueba de edicion")
    self.driver.find_element(By.CSS_SELECTOR, "div > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-item:nth-child(4) .navbar-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product:nth-child(13) .delete-button").click()
  
