# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCRUDUsuario():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cRUDUsuario(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(1510, 697)
    self.driver.find_element(By.CSS_SELECTOR, ".cta > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(3) > span").click()
    self.driver.find_element(By.NAME, "email").send_keys("grupo17@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()

        # Espera y maneja el pop-up (alerta) que aparece después de iniciar sesión
    WebDriverWait(self.driver, 10).until(
        expected_conditions.alert_is_present()
    )
    alert = self.driver.switch_to.alert
    alert.accept()  # Hace clic en "OK" en el pop-up
    
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(4) > .navbar-link").click()
    self.driver.find_element(By.LINK_TEXT, "Registrar Usuario").click()
    self.driver.find_element(By.NAME, "first_name").click()
    self.driver.find_element(By.NAME, "first_name").send_keys("Prueba")
    self.driver.find_element(By.NAME, "last_name").send_keys("Prueba")
    self.driver.find_element(By.NAME, "email").send_keys("prueba@gmail.com")
    self.driver.find_element(By.NAME, "username").send_keys("prueba")
    self.driver.find_element(By.NAME, "password").send_keys("1234")
    self.driver.find_element(By.NAME, "confirm_password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".usuario-item-Cliente:nth-child(8)").click()
    self.driver.find_element(By.NAME, "is_staff").click()
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".usuario-item-Admin:nth-child(8) > .delete-button").click()
    self.driver.switch_to.alert.accept()
  
